dotenv: .env

wallets:
  DEPLOYMENT_PRIVATE: ${DEPLOYMENT_PRIVATE}
  OWNER_PRIVATE: ${OWNER_PRIVATE}
  FEN_DEPLOYMENT_PRIVATE: ${FEN_DEPLOYMENT_PRIVATE}
  FEN_OWNER_PRIVATE: ${FEN_OWNER_PRIVATE}


compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
    vyper:
        version: null